# Generated by Django 4.1.7 on 2023-04-02 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=63, null=True)),
                ('description', models.CharField(max_length=255, null=True)),
                ('executor', models.CharField(max_length=31)),
                ('supervisor', models.CharField(max_length=31)),
                ('status', models.CharField(choices=[('TD', 'To do'), ('IP', 'In progress'), ('FI', 'Finished')], default='TD', max_length=2)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(null=True)),
                ('planned_time', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_status', models.CharField(choices=[('TD', 'To do'), ('IP', 'In progress'), ('FI', 'Finished')], max_length=2)),
                ('next_status', models.CharField(choices=[('TD', 'To do'), ('IP', 'In progress'), ('FI', 'Finished')], max_length=2)),
                ('changed_by', models.CharField(max_length=31)),
                ('task', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='statuses', to='main.task', verbose_name='Изменение статуса')),
            ],
        ),
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=255)),
                ('users', models.CharField(max_length=255)),
                ('task', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reminders', to='main.task', verbose_name='Напоминание')),
            ],
        ),
    ]
